### ISSUE TITLE
MSAL Installation

### ISSUE THREAD

**Issue by the03ennis** [milestonetg/msal-js-dart#11]
First off, let me preface by saying my knowledge of JavaScript is rudimentary at best.
I'm trying to install the MSAL Library itself so that the flutter project can see it, and I'm at a complete loss.

Just to get started, I've copied and pasted the web example. Then, I downloaded the MSAL library from npm and moved it into my lib folder.

I've also tried adding some script declarations to the body of the index.html.

The ultimate goal is to get this working cross platform (web/android/iOS), and I know that I'm doing something wrong and I would appreciate a little guidance.

**Comment by Francessco121** [comment]
When you created your Flutter app it should have created a `web` folder. This is the "root" of your Flutter app when it's running on the web. In the `web` folder should be an `index.html` file, which is what actually launches your Flutter app by loading its compiled `main.dart.js` file. The `index.html` file needs to also reference `msal.js`, before `main.dart.js`.

To get msal.js in there you have two options:
- Reference the [msal.js CDN](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-JS-CDN-URL-and-SRI-Hash) in your `index.html` file's `<head>`: `<script src="https://alcdn.msftauth.net/lib/1.3.2/js/msal.min.js"></script>`
- Download a build of msal.js either from the NPM package or directly from their CDN and store it somewhere in your `web` folder, then reference it in your `index.html`: `<script src="msal.min.js"></script>`

Since Dart can't import/understand NPM packages, there's no way to just install it through that and have it work. Instead of importing MSAL like a module, this package just uses the global JavaScript objects that msal.js exposes when it loads on a web page.

If you're still having trouble after that, make sure you're using MSAL correctly. Take a look at the [Flutter example here](https://github.com/milestonetg/msal-js-dart/blob/master/example/flutter_web_example.md) if you haven't already. There's some minor things to keep in mind when using this package with Flutter that are noted in it. Also please make sure you're using at least version 1.2.2 of this package, as that version fixed issues with Flutter running in release mode.

As for supporting cross-platform, this package will only get you web support. If you want to support all three of those platforms, you'll need to use this package *and* an Android/iOS MSAL library such as [`package:msal_flutter`](https://pub.dev/packages/msal_flutter) or [`package:msal_mobile`](https://pub.dev/packages/msal_mobile). From there, you can select which MSAL package to use depending on the platform using [Dart conditional import/exports](https://dart.dev/guides/libraries/create-library-packages#conditionally-importing-and-exporting-library-files).

**Comment by the03ennis** [comment]
Thank you for the help!
