### ISSUE TITLE
Cannot read property 'Logger' of undefined

### ISSUE THREAD

**Issue by remymumoh** [milestonetg/msal-js-dart#17]
**Describe the bug**

**To reproduce**
1. set up the client id` const String clientId=' '`
2. setup client authority  `const String authority = 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize';`
3. setup the scope `const List<String> scopes = ['openid profile email'];
`
**Expected behavior**
Am expecting a redirect to azure AD,  instead that error is thrown

**Screenshots**
![image](https://user-images.githubusercontent.com/10322082/100786829-c3e50d00-3423-11eb-9a5e-9afc27692292.png)

**Environment (please complete the following information):**
 - Flutter: [yes]
 - Browser: [chrome]
 - Dart msal_js Version: [dart: ">=2.12.0-0.0 <3.0.0"]
 - JavaScript msal.js Version: [ msal_js: ^1.3.0]

**Additional context**

**Comment by Francessco121** [comment]
It appears that msal.js (the JavaScript library) is never loaded. This package does not come with a build of msal.js, [you can download it here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/cdn.md). Can you confirm that you're loading it in your index.html, and if so what version of the JavaScript msal.js library are you using?

**Comment by remymumoh** [comment]
adding the msal.js works, you need to have a better documentation for newer people like me to flutter
how do you set up the pop to azure login,

tried it like this 
```
const String authority = 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize';
const List<String> scopes = ["openid", "profile", "email"];
```

not getting the azure page to start to allow me to login?

**Comment by Francessco121** [comment]
This Dart package is just a wrapper over msal.js. You need to read through [their documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-core#usage) before using this package. We do have a simple [Flutter example](https://github.com/milestonetg/msal-js-dart/blob/master/example/flutter_web_example.md) with some Flutter-specific considerations documented.

The authority should not be a direct URL to the `/authorize` endpoint and it depends on which type of Active Directory you're using. Please refer to [their documentation here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-client-application-configuration#authority). If you're using Azure B2C, see the "B2C specifics" link on that page.

The msal.js library automatically adds the `openid` and `profile` scopes for you since the library requires them to function. That may or may not be part of your issue, I can't remember if they generate an error if you specify them yourself.

**Comment by Francessco121** [comment]
Closing this for now. If you're still having trouble, please comment back here or open a new issue.

**Comment by remymumoh** [comment]
how do you set a reply url, I have configured my configs well on azure ad, but I keep ending up with the error 
`AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: '8b504844-37db-4b52-bfb0-963b66fcf1b2'.`

How did you set up your config for the app to login well and show the logged in userrname?

**Comment by Francessco121** [comment]
[As stated in the MSAL docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-initializing-client-applications), the redirect URI is set in the configuration of the `UserAgentApplication`:
```dart
// Dart example
final userAgentApplication = UserAgentApplication(
  Configuration()
    ..auth = (AuthOptions()
      // Can be either a URI or a function returning a URI
      ..redirectUri = 'your-redirect-page'),
);
```

> How did you set up your config for the app to login well and show the logged in userrname?

If you're referring to the Flutter example, in our case we're using Azure B2C so:
- `clientId` is our Active Directory app registration client ID
- `authority` is `https://<tenant>.b2clogin.com/tfp/<tenant>.onmicrosoft.com/<policy>`
- `scopes` is a single scope for our API resource
- `redirectUri` **(which is not in the example, but needed as we have a custom redirect URI presumably like you)** is just the index page of the app

Other than that, it's done just like the example shows. I can't really speak for non-B2C stuff, haven't used them before. I know msal.js's docs can be tricky but all the info is in there.

**Comment by remymumoh** [comment]
Am pretty new to flutter, adding the  `..redirectUri = 'your-redirect-page'), ` i end up with the error `The setter 'redirectUri' isn't defined for the type 'Configuration'.`
